config/routes.rb
Rails.application.routes.draw do
  get 'pages/home'
  # Users
  get "/sign-up", to: "users#new", as: "sign_up"
  post "/sign-up", to: "users#create"
  get "/dashboard", to: "users#show", as: "dashboard"

  # Sessions
  get "/sign-in", to: "sessions#new", as: "sign_in"
  post "/sign-in", to: "sessions#create"
  delete "/sign-out", to: "sessions#destroy", as: "sign_out"

  # Tee Times
  post "/tee-times", to: "tee_times#create", as: "tee_times"
  get "/tee-times", to: "tee_times#index"#, as: "tee_times"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/longmont_tee_time.rb
class LongmontTeeTime
  attr_reader :time, :spots_available, :min_players, :rates
  
  def initialize(object)
    @time = object.teetime.to_datetime.in_time_zone("Mountain Time (US & Canada)")
    @spots_available = object.maxPlayers
    @min_players = object.minPlayers
    @rates = object.rates
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user

  def redirect_user
    redirect_to dashboard_path if current_user
  end

  def require_user
    redirect_to sign_in_path unless current_user
  end
  
  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_user, only: [:new, :create]
  
  def create
    @user = User.find_by(email: params[:email])
    if @user&.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:alert] = "something went wrong"
      render :new
    end
  end
  
  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have been signed out."
    redirect_to sign_in_path
  end
end

app/controllers/tee_times_controller.rb
class TeeTimesController < ApplicationController
  def index
    @courses = TeeTimesService.call(date: params[:date], location: params[:location])
    @date = params[:date]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_user, only: [:new, :create]
  before_action :require_user, only: [:show]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      flash[:alert] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= vite_client_tag %>
    <%= vite_stylesheet_tag 'application', data: { "turbo-track": "reload" } %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

    <%= vite_client_tag %>
    <%= vite_javascript_tag 'application' %>
    <!--
      If using a TypeScript entrypoint file:
        vite_typescript_tag 'application'

      If using a .jsx or .tsx entrypoint, add the extension:
        vite_javascript_tag 'application.jsx'

      Visit the guide for more information: https://vite-ruby.netlify.app/guide/rails
    -->

  </head>

  <body>
    <%= render partial: "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<%= content_tag(:div, "", id: "app")%>

app/views/shared/_navbar.html.erb
<% if current_user %>
  <%= button_to "Sign Out", sign_out_path, method: :delete, class: 'bg-gray-100 hover:bg-gray-300 text-gray-800 font-semibold py-1 px-4 border border-gray-900 rounded shadow' %>
<% end %>

app/views/tee_times/index.html.erb
<%= link_to "Dashboard", dashboard_path, class: "font-medium text-blue-600 dark:text-blue-500 hover:underline" %>

<h2>Date: <%= @date %></h2>

<div class="tee-time-tables">
  <% @courses.each do |course_name, tee_times| %>
    <table class="tee-times table-auto">
      <thead>
        <tr>
          <th class="px-4 py-2">
            <%= course_name.to_s.titleize %> - <%= tee_times.count %>
          </th>
        </tr>
      </thead>
      <tbody>
        <% tee_times.each do |tt| %>
          <tr>
            <td class="border px-4 py-2">
              Time: <%= tt.time.strftime("%l:%M %P") %><br />
              Spots available: <%= tt.spots_available %><br />
              Minimum players: <%= tt.min_players %><br />
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/users/new.html.erb
<div>
  <h2>Sign Up</h2>  
  <%= form_with model: @user, url: sign_up_path do |f| %>
    <div>
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
    <div>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div style="padding:50px;">
  <h1 class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-5xl lg:text-6xl dark:text-white">Dashboard</h1>
  <h4  class="mb-4 text-4xl font-extrabold leading-none tracking-tight text-gray-900 md:text-2xl lg:text-3xl dark:text-white">When and where do you want to play golf?</h4>
  <%= form_with url: tee_times_path, method: :get, local: true do |f| %>
    <div class="mb-4">
      <%= f.label :date, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= f.date_field :date, value: Date.tomorrow, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" %>
    </div>
    <div class="mb-4">
      <%= f.label :location, class: "block uppercase tracking-wide text-gray-700 text-xs font-bold mb-2" %>
      <%= f.select :location, ["Longmont", "Denver (not yet, coming soon)"], {}, {class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"} %>
    </div>
    <%= f.submit "See Tee Times", class: 'bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded' %>
  <% end %>
</div>